name: CI
on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y git
      - name: Install dotfiles
        run: .bin/install.sh